msm: camera: isp: fix -Wmisleading-indentation
Fixes:
drivers/media/platform/msm/camera_v2/isp/msm_isp40.c:237:7: error:
misleading indentation; statement is not part of the previous 'for'
[-Werror,-Wmisleading-indentation]
kfree(ds_regs);
^
drivers/media/platform/msm/camera_v2/isp/msm_isp40.c:234:6: note:
previous statement is here
for (i = 0; i < ds_entries; i++)
^

Nothing interesting here, someone just forgot to `set tabstop=8`.

Bug: 155426751
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
Change-Id: Iefafdc35ed6d5be7ffc29fb7cc4ca181efe54a9b