mm: zsmalloc: fix build error after recent commits
Commit ff9e3e0f2d13ef0d8edb6fc3fa4417f14cd31a6a and 09beeb4694414e6dd40f947096bc07ab3fa169d4 (from upstream) are conflicting.

Fixes the following error:

../mm/zsmalloc.c:465:9: error: returning 'atomic_long_t' (aka 'atomic64_t') from a function with incompatible result type 'unsigned long'
        return stats.pages_compacted;
               ^~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Joel Gómez <nahuelgomez329@gmail.com>