drivers: rtl8812au: Guard `-Wno-cast-function-type` when using Clang
If this is used with Clang, it can lead to the following errors:

error: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Werror,-Wunknown-warning-option]
  CC [M]  drivers/staging/rtl8814au/core/rtw_ioctl_set.o
make[4]: *** [../scripts/Makefile.build:364: drivers/staging/rtl8812au/core/rtw_cmd.o] Error 1
make[4]: *** Waiting for unfinished jobs....
error: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Werror,-Wunknown-warning-option]
make[4]: *** [../scripts/Makefile.build:364: drivers/staging/rtl8812au/core/rtw_security.o] Error 1
  CC [M]  drivers/staging/rtl8814au/core/rtw_ieee80211.o
error: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Werror,-Wunknown-warning-option]
  CC [M]  drivers/staging/rtl8814au/core/rtw_mlme.o
make[4]: *** [../scripts/Makefile.build:364: drivers/staging/rtl8812au/core/rtw_debug.o] Error 1
make[3]: *** [../scripts/Makefile.build:678: drivers/staging/rtl8812au] Error 2
make[3]: *** Waiting for unfinished jobs....

Signed-off-by: Joel Gómez <nahuelgomez329@gmail.com>